name: deploy Telegram Bot

on:
  push:
    branches: 
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v3
    
    - name: login to docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: build docker image
      run: docker buildx build --platform linux/amd64 -t km136/my-tg-bot:latest

    - name: push docker image
      run: docker push km136/my-tg-bot:latest

    - name: deploy to render
      run: |
        curl -X PATCH "https://api.render.com/v1/services/srv-d2ng3g3e5dus7380gbig" \
        -H "Authorization: Bearer ${{ secrets.RENDER_API_TOKEN }}" \
        -H "Content-Type: application/json" \
        -d '{"dockerImage":"docker.io/km136/my-tg-bot:latest"}'
